language: node_js

node_js:
  - 8
  - node

os:
  - linux

matrix:
  allow_failures:
    - node_js: node
  fast_finish: true

sudo: false

cache:
  npm: true
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - export CXX=g++-4.8; export CC=gcc-4.8;

before_script:
  - createdb db_migrate_test
  - cp test/db.config.ci test/db.config.json
